### ISSUE TITLE
2017-06-29 BKKHack

### ISSUE THREAD

**Issue by waf** [bkkhack/hackmap#1]
Welcome to BKKHack!

If you know what you'll be hacking on, add it to the left. When you arrive at the event, drag your picture to the seat diagram below so others can find you!

If you're not sure, you can join somebody else's hack, or ask Ches or Dylan if you have any questions.

**Comment by waf** [comment]
Test
Test2

Test3

**Comment by waf** [comment]
asdf
asdf

**Comment by waf** [comment]
Vue
I'm working on Vue JS!

**Comment by waf** [comment]
VueJS

**Comment by waf** [comment]
Foo

**Comment by djay** [comment]
wifi:enginex: 1234567890
And maybe other aspects of the UX

**Comment by shanetorr** [comment]
Trello - how to use it better?

**Comment by ghost** [comment]
Amazon Web Services

**Comment by keithrbennett** [comment]
Android Development Setup
I want to set up an Android development environment on my Mac, and hopefully create a minimal Android app as a test. I plan to choose Kotlin as the language (with which I am not yet familiar), but anyone can choose Java too. An Android device is not required, as there are emulators. Anyone else wanting to work with me with or without putting it on your own machine?

**Comment by umarkhan81** [comment]
Hack to fight online violence/harassment
Creating a platform for reporting acts of online harassment towards women and marginalized groups in particular.

**Comment by sophyphreak** [comment]
freeCodeCamp
Front End:
HTML5, CSS3, Bootstrap, JQuery, Javascript

Data Visualization:
React.js, D3

Back End:
Node.js, Express.js, Git, MongoDB

Job search advice

**Comment by marcuslind90** [comment]
Angular4 + Django
For fun!

**Comment by marcuslind90** [comment]
Angular4 + Django
For fun!

**Comment by aljones15** [comment]
Haskell then Om.Next
updating a haskell project and then looking at Om.Next

**Comment by pangaunn** [comment]
Vuex
we are going to build simple counter game with vuex.

**Comment by waf** [comment]
Test 4
Another test !

**Comment by Pongch** [comment]
Learning Rails

**Comment by Pongch** [comment]
Learning Rails

**Comment by markusenglund** [comment]
React production website

**Comment by BliztRipper** [comment]
Angular Google Map (AGM) + Firebase

**Comment by 6xiri** [comment]
Building a Travel Game App 0-100
0-100 is like from scratch, I don't know much about code but I'd like to form a team to bring my idea to life. contact me for more details and if you know xCode and speak swift.

**Comment by 31o5** [comment]
App design prototype
I want to build an app to make co-parenting easier. Just started sketching and working on design prototype.

I'm design/frontend person, so I'll need someone to join me to build an actual app. At this moment it's still forming concepts but will be really nice to discuss with devs and parents.

**Comment by salinceva** [comment]
Hardware hackers
Arduino raspberry pi and functional hacks

**Comment by passakornC** [comment]
Angular 4 + WebAssembly

**Comment by abzeede** [comment]
Develop Pomodoro timer App with React native
