### ISSUE TITLE
2017-08-31 BKKHack

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#12]
Welcome to BKKHack!

If you know what you'll be hacking on, add it to the left. When you arrive at the event, drag your picture to the seat diagram below so others can find you!

If you're not sure, you can join somebody else's hack, or ask Ches or Dylan if you have any questions.

**Comment by djay** [comment]
work on hackmap
wifi enginex_5g:1234567890

**Comment by orelmax** [comment]
Frontend (react)
Open for ideas

**Comment by cloudgate313** [comment]
Frontend NG4 / React
Would like to build something in React to gain experience.  Primarily work with Angular 4 at wrok.

**Comment by passakornC** [comment]
Angular 4 + WebAssembly

**Comment by jean** [comment]
Parsing UMLet diagrams with Python
Exploring parsers like http://pyparsing.wikispaces.com/
and https://github.com/igordejanovic/textX

**Comment by elcolie** [comment]
Chatbot
1. Play with Chatbot

**Comment by hungle88** [comment]
Integrate D3 with React App
I would like to learn more about D3Js by building something called a "Sport Team Report Dashboard". While it sounds a bit complicated but we'll be building only 2 reports:

- A Diversity Map showing how many players come from which country. 
- A Position Pie/Bar Chart showing how many players that play at each position (eg 10 defenders, 6 middle fields.. )

The data set that I have might allow we build more charts such as attendance list or single match report but let see if we have enough time.  

This will be built with React as well so if you're looking to gain some experience with React this might be a good opportunity.

**Comment by steve1rm** [comment]
Android
Build an Android app

**Comment by heetren** [comment]
R
I'm analyzing customer retention and churn in R to build a predictive model

**Comment by bmason** [comment]
Erudite View
http://myally.co/erudite-view

**Comment by stubborngaurav** [comment]
C#
C# for games

**Comment by VictorPlante** [comment]
Python beginner
I am beginner to Python, I am looking to meet coding beginners ready to share and learn together.

**Comment by VictorPlante** [comment]
Python beginner
I am beginner to Python, I am looking to meet coding beginners ready to share and learn together.

**Comment by waf** [comment]
hackmap

features and bugfixes

**Comment by siwatjames** [comment]
Beginner
I am a beginner in programming with little experience, know a little bit of Javascript, PHP, and now interested in learning Python.

**Comment by ches** [comment]
Learn GraphQL, with Scala
Getting familiar with GraphQL in general, so regardless of your language preferences feel free to join if you're also curious or already have knowledge to share.

I'm particularly interested in how to integrate a GraphQL server implementation with an application's data access layer (potentially mixed relational or non-relational), so I'll be looking at [Sangria](http://sangria-graphql.org/) for Scala.

If no one else jumps in I might instead try to help @waf and @djay with the hackmap :relaxed:

**Comment by bushono** [comment]
Python
Will be working on my own project called Scaffolder CLI - a tool for managing aPaaS.

**Comment by abadikaka** [comment]
Newbie
Learn more about front-end or mobile development

**Comment by vemvemvem** [comment]
NodeJS simple app

**Comment by pmdscully** [comment]
TourPlanner

**Comment by ad19** [comment]
Julia
Julia, JuliaBox, maths

**Comment by ad19** [comment]
Julia, JuliaBox + math

**Comment by sophyphreak** [comment]
FreeCodeCamp
Beginners welcome!

**Comment by nitnoiPHS** [comment]
Python beginner ++

**Comment by ohmatey** [comment]
Hackmap
Work on mobile first

**Comment by naisk133** [comment]
Scala

**Comment by starace1213** [comment]
Newbie
Tiny bit of C

Almost useless

**Comment by phonxvzf** [comment]
Graphics programming with C++

**Comment by zunpitchk** [comment]
Python beginner
Goal: Export excel to Access using CPython

**Comment by blead** [comment]
GraphQL & JS in general
Building a GraphQL server for a museum in Chula.
May work on other things if I feel like.

**Comment by markwk** [comment]
Data Hacking
Hacking on self-tracking data (processing, visualizations, maybe modeling) with R, Tableau, Gretl, and maybe python. Backend and web visualizations time? May work on other things if I feel like it.

**Comment by bighappyworld** [comment]
SMTP
Building a simple deployable SMTP / IMAP server. see haraka and wildduck

**Comment by peawyoyoyin** [comment]
React Native
I'm developing a mobile app using React Native (ongoing project)

**Comment by peawyoyoyin** [comment]
React Native

**Comment by Poomchaio** [comment]
ios app

**Comment by Poomchaio** [comment]
iOS application

**Comment by Poomchaio** [comment]
iOS App

**Comment by phootip** [comment]
React
Learn the React tutorial (tic tac toe)

**Comment by dreamstocode** [comment]
Writing a bot in NodeJS to play Ruby Warrior
Ruby Warrior (RW) is a nice way to learn programming and explore the Ruby. I'd like to learn more about node and Selenium so I thought it would be fun to combine all three and write a bot to play RW for me.

RW: https://www.bloc.io/ruby-warrior#/

**Comment by dreamstocode** [comment]
Create a bot in NodeJS to play Ruby Warrior

**Comment by dreamstocode** [comment]
Create a bot in NodeJS to play Ruby Warrior
Ruby Warrior is a nice way to learn programming, problem solving and logic. I'd like to learn NodeJS, and web testing and I'd thought it would be fun to combine all 3 and write a bot to play RW for me.

https://www.bloc.io/ruby-warrior#/

**Comment by dreamstocode** [comment]
Create NodJS bot to play Ruby Warrrior

**Comment by dreamstocode** [comment]
Ruby Warrior Bot with NodeJS

**Comment by tao-pr** [comment]
Computer Vision, OpenCV3
Will be trying to implement AAM (Active Appearance Model) with OpenCV3 C++. There are plenty of AAM libraries but none of them operates on OpenCV as new as version 3. So I decided to make my own.

**Comment by markwk** [comment]
Data Science Hacking / React Native
Either work on quantified self tracking data stuff with R, Tableau and/or python  OR react-native. It depends...

**Comment by cloudgate313** [comment]
This sounds interesting.


Evan

**Comment by pangaunn** [comment]
hackmap
Features.

**Comment by yutita** [comment]
hackmap (Vue.js)

**Comment by jean** [comment]
Termux (Linux userland on Android)
pull request; `bash-it`; compiling `lxml`

**Comment by markusenglund** [comment]
react component for npm

**Comment by sthapaun** [comment]
golang
Golang

**Comment by p-rial** [comment]
Newbie

**Comment by brendonmatheson** [comment]
Wildebeest - Very Easy Database Migrations
Wildebeest is a migration framework designed to solve the problem of reliably migrating stateful system resources such as databases or file structures in continuous deployment projects

https://github.com/zendigitalstudios/wildebeest
http://zendigital.co/wildebeest/

**Comment by dreamstocode** [comment]
Creating a bot to play Ruby Warrior in NodeJS
I wanted to learn more about NodeJS and auto testing and thought it would be fun to try and create a bot to play Ruby Warrior.

**Comment by frawau** [comment]
Python Learning
Just a learning group

**Comment by natpasukit** [comment]
socket webrtc
Either doing webRTC and socket.io for real time chat app or playing with vuejs / GraphQL / go
