### ISSUE TITLE
Handle github's auto-generated avatar images

### ISSUE THREAD

**Issue by jean** [bkkhack/hackmap#16]
They're showing up huge.

![avatars](https://user-images.githubusercontent.com/84800/29858163-5a6af41c-8d86-11e7-8f16-a11e35d3d05a.png)

**Comment by waf** [comment]
yeah, weird. Github used to resize them to us, but they stopped respecting that url parameter, apparently. Could be a bug on their side. For now, I've deployed a css change to fix it quickly, I'll do a longer term fix for this soon. Thanks!
