### ISSUE TITLE
Auto-link URLs – or can we get fully-rendered GitHub Flavored Markdown?

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#17]
People often include URLs in their hacks for the technology or project that they're going to work with/on. Currently these aren't clickable in the hackmap UI.

Presumably you can already enter Markdown syntax when adding a hack, if you're in the know. Can we also get pre-rendered GFM from the API, so that in addition to URLs other things like @ches will be a link to user profiles, etc.? And let's not forget emoji, who could live without them anymore? 🌮 🎉

**Comment by waf** [comment]
Just prototyped this, and it's definitely possible. Even better -- we can get all the markdown rendered in a single http request. I was worried we'd have make a request per project.

From here: https://developer.github.com/v3/issues/comments/#custom-media-types

We can send the following media type in our comments ajax request, and the json will contain a `body_html` property with rendered html and links (and emoji❗️).

```
Accept: 'application/vnd.github.VERSION.html+json'
```

Some of the deserialization code (from issue comment text to our project object) will need to be revisited, but it shouldn't be too difficult.

**Comment by waf** [comment]
Completed in https://github.com/bkkhack/hackmap/pull/48. We now have full GitHub Flavored Markdown support, including emoji :shipit:
