### ISSUE TITLE
Set up a test framework, Travis build

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#22]
I'm afraid of breaking things when changing an unfamiliar code base without some tests to help me spot regressions 😊 

The Vue.js docs [suggest Karma][1], but most popular frameworks can work. @waf do you have any preference?

[1]: https://vuejs.org/v2/guide/unit-testing.html

**Comment by waf** [comment]
We definitely need these. This prototype app somehow made it to production! i've never used Karma, but I'm all for learning new things. Thanks for looking into this and opening the issue!

**Comment by waf** [comment]
Fixed in https://github.com/bkkhack/hackmap/pull/33
