### ISSUE TITLE
Layout is bad on Android Firefox

### ISSUE THREAD

**Issue by jean** [bkkhack/hackmap#25]
Layout is quite bad on Firefox, the left column doesn't scroll independently and the table part is too small.

![screenshot_20170928-193204](https://user-images.githubusercontent.com/84800/30966612-bef24d22-a483-11e7-8e25-d3e0a10ab1e6.jpg)

Samsung Galaxy Tab A 10"

**Comment by waf** [comment]
Can you please check it out now? There's been a redesign that should improve the layout. It's still not amazing on mobile, but it should at least be usable now. Here's what it looks like on my android tablet (nexus 10):

![hackmap](https://user-images.githubusercontent.com/97195/37215048-73afbdf0-23e9-11e8-993a-553d8c284311.png)

**Comment by waf** [comment]
I'm going to close this, because I think the new layout solves the issue. Thanks for reporting it! Please re-open this or enter a new issue if you find anything else!
