### ISSUE TITLE
Pet hate: showing "you're the first!" if you mean "the network is slow :-("

### ISSUE THREAD

**Issue by jean** [bkkhack/hackmap#26]
![smartselectimage_2017-09-28-19-41-49](https://user-images.githubusercontent.com/84800/30967125-62fd58e8-a485-11e7-8d4c-abab90ad0840.png)

**Comment by waf** [comment]
Agreed. We should have different messages for "no comments because we're loading" and "no comments because nobody commented"

**Comment by jean** [comment]
Related: https://github.com/bkkhack/hackmap/issues/30

**Comment by djay** [comment]
Fix is in #40 I believe

**Comment by waf** [comment]
#40 will help with this message showing in error scenarios, but we'll need an additional PR that shows a loading message in the 2-3 seconds where we're waiting for the initial API request to complete (on page load).
