### ISSUE TITLE
Auto-unsubscribe from the hackmap issue after posting

### ISSUE THREAD

**Issue by waf** [bkkhack/hackmap#29]
From discussion on https://github.com/bkkhack/hackmap/issues/10 by @ches:

> everyone who adds a hack gets subscribed to the issue and gets email notifications for subsequent posts—kind of cool network effect of hearing about what others are doing, but also potentially annoyingly noisy to some

Initial thought is for the app to call [DELETE /notifications/threads/:id/subscription](https://developer.github.com/v3/activity/notifications/#delete-a-thread-subscription) (or some other API?) to prevent email notifications.

**Comment by djay** [comment]
@ches @waf I think notifications are a feature rather than a problem as long as they are only on new comments/hacks rather than every update or move.
We could have a button on the page for users to optionally unsubscribe though.

**Comment by waf** [comment]
closing this, as it's not clear if it's a bug or a desired feature 😄 

each notification sent from github comes with a direct link to unsubscribe, so I think that's fine.
