### ISSUE TITLE
January 2018 Hack Night

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#38]
Welcome to BKK/hack!

If you know what you'll be hacking on, add it to the left.

The seating chart may not be up-to-date yet, but go ahead and add your plan or idea—when you arrive at the event, drag your picture to where you're sitting so others can find you.

If you're not sure, you can join somebody else's hack, or ask @ches or @djay if you have any questions.

**Comment by ches** [comment]
The seating chart may not be up-to-date yet, but go ahead and enter your plan or idea!

**Comment by ches** [comment]
Get Ready
The seating chart may not be up-to-date yet, but go ahead and enter your plan or idea!

**Comment by delta-9** [comment]
Golang / React: Trading tools using exchange API
Implements some basic tools for trading such as buy / stop loss order, overview of a portfolio, panic sell button.
I also have some knowledge of solidity / smart contract if people are working on that I can join.

**Comment by richsmith92** [comment]
"Reinventing blockchain" mind map
Bitcoin blockchain was an answer to a problem which most of people were never concerned about in the first place. I think this explain why so many people have trouble understanding it.

I'll be working on a presentation in form of a mind map or decision tree, to show what kind of evolution of thought could lead to Bitcoin design.

My initial draft: https://atlas.mindmup.com/2018/01/06722020fdb511e78962cf9ef6a6d69d/blockchain/index.html

Anyone is free to join. If you are new to cryptocurrencies, I think it's even better, because you won't have the curse of knowledge.

**Comment by timthetanker** [comment]
MyBru
Make Sporting predictions- A sport prediction game

**Comment by elcolie** [comment]
React Testing
Testing by using facebook incubator

**Comment by dwsmith1983** [comment]
Whatever happens
We will see

**Comment by ghost** [comment]
Python/ Kivy
Make tapping numbers game

**Comment by djay** [comment]
Kodi python plugin for social watching
Wifi: Learn Hub+ Guest
User: bkkhack
PW: bkkhack

**Comment by nootanghimire** [comment]
dafuq.is backend
A collection of python scripts that powers a rather useless website called: https://dafuq.is . It basically gives you definitions of a word or phrase by pulling it out of urban dictionary, but I do have some novel plans. 

Mostly Targeted towards leaning python.

**Comment by jean** [comment]
Styling markdown/RST using bootstrap
Styling the Python Conference Thailand website using Bootstrap.

**Comment by ches** [comment]
Hackmap features and fixes
Might work on the Hackmap, this thing you might be viewing right now.

It's a client-side Vue.js application that uses GitHub as a datastore. The source repository lives here:

https://github.com/bkkhack/hackmap

@waf can help answer questions about the project and may work on it as well.

**Comment by waf** [comment]
Hackmap or .NET IL
Either helping out with the HackMap, or working on the .NET intermediate language (IL) backend for my programming language.

**Comment by Robert-Ernst** [comment]
NodeJs Basics (i.e. promise)
Teaching some NodeJS if anyone is interested to join.
Topic is at least promises

**Comment by smalldatabrains** [comment]
Google Cloud API, play with machine learning tools (Python)

**Comment by disconnect3d** [comment]
Pwndbg or CTFs
This will be one of:

- developing/improving a GDB plugin written in Python for debugging low level code (yeah, assembly!) ( see https://github.com/pwndbg/pwndbg )

- solving some wargames/capture the flag contest challenges (security related stuff; see https://ctftime.org/ctf-wtf/ or https://www.youtube.com/watch?v=8ev9ZX9J45A ) - we could go with some easy challenges, solve and explain them together

**Comment by kidchenko** [comment]
React

**Comment by nadam** [comment]
Cryptocurrency exchange bot
Telegram bots interacting with exchanges

**Comment by crishoj** [comment]
iOS port of thai-language.com (C#/Xamarin)

**Comment by brendonmatheson** [comment]
Wildebeest
Wildebeest - the best database migration tool in the colonized worlds - http://zendigital.co/wildebeest/

**Comment by ankitpokhrel** [comment]
dafuq.is backend
...

**Comment by mrik23** [comment]
React (learning)

**Comment by marcinkaszynski** [comment]
Golang for Python devs
I'm preparing workshops on Go for Python devs.  Could also help with another project in Go or Python.

**Comment by saiqulhaq** [comment]
Fixing Hackmap

**Comment by dflamholc** [comment]
Python
Vfx software GUI for filename convention

**Comment by vehas** [comment]
clojure
we will write 3 connected micro service with clojure and scala , save simple data to redis db
and load test it. Any body welcome,  we're happy to train you to be clojurian  and scala practitioner.

**Comment by jaspervz** [comment]
Scala microservice
With http4s and doobie

**Comment by ditsara** [comment]
If you want to learn Rails see me

**Comment by scomma** [comment]
Fishtank
Fishtank is like a screensaver for your corporate lobby. It displays organic bits of data that were just entered into your SaaS in realtime, for vanity purposes.

Stack: whatever gets it done quickest.

**Comment by ginegine** [comment]
UX designer

**Comment by ginegine** [comment]
UX Designer

**Comment by mikey1384** [comment]
open source social network website
www.twinkle.network
https://github.com/mikey1384/twin-kle

**Comment by PePoDev** [comment]
Game Development (Unity3d,C#,3D model,Graphics UI)
(First time) I want to create a game to push to the Google Play Store.
I have an idea, but I want a friend to help me make this game a success. We will share the knowledge . And make friendship between each other.
