### ISSUE TITLE
need to be able to configure the map/background and title

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#4]
probably as part of the main comment

- [x] Update map
- [x] Update title

**Comment by waf** [comment]
Commit 900387bd672ee594caaeeee8247ff87489d1b192 adds the ability to configure the title. It uses the issue title (e.g. "March 2018 Hacknight")

**Comment by waf** [comment]
PR https://github.com/bkkhack/hackmap/pull/50 adds updating the floorplan image.
