### ISSUE TITLE
Quick labels on the map (+ background?)

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#41]
I want a way to overlay text quickly on the map like WiFi PW or table themes. It would also be good be able change the map or put new things on top. Only by admin.

Could be implemented as editing the description of the haclnight issue and above each item to be placed embed code for position and size. 

UI would click on paragraph in description and click "place" and you move and resize visually. Map last and labels at the top.

**Comment by djay** [comment]
This would superceed https://github.com/bkkhack/hackmap/issues/4 at least for the background

**Comment by djay** [comment]
@waf I guess for now, since #4 is done, we can just edit the image often and set labels and other text on it.

**Comment by waf** [comment]
Alternately, we could use a solution that's independent of hackmap, e.g. something like [this chrome extension](https://chrome.google.com/webstore/detail/web-paint/emeokgokialpjadjaoeiplmnkjoaegng?hl=en).

I think most operating systems have some concept of sticky notes, which would work for the wifi password.

**Comment by djay** [comment]
I think that would be fine. Can the app poll the image so it gets updated
if it changes?

**Comment by waf** [comment]
No, the app doesn't poll the background image, and I think we would run into more rate limiting problems if we added it.
