### ISSUE TITLE
February 2018 Hack Night

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#43]
Welcome to BKK/hack!

If you know what you'll be hacking on, add it to the left.

The seating chart may not be up-to-date yet, but go ahead and add your plan or idea—when you arrive at the event, drag your picture to where you're sitting so others can find you.

If you're not sure, you can join somebody else's hack, or ask @ches or @djay if you have any questions.

**Comment by bmason** [comment]
A smalltalk like PHP code browser/explorer

**Comment by JesseSoldat** [comment]
React / Node simple CRUD app
Just playing around with react / node. I would love to get some advice from someone with more experience with the two technologies

**Comment by disconnect3d** [comment]
Pwndbg or Manticore
I will work on one of the projects:
* Pwndbg - a plugin for GDB that makes it easier to debug native code [cool interface for debugging assembly code or reverse engineering stuff] - https://github.com/pwndbg/pwndbg

* Manticore - a symbolic execution engine for analysing binaries or smart contracts - https://github.com/trailofbits/manticore

**Comment by codecoded** [comment]
Tournament.gg website
Continuing to work on a personal website that I do with a friend - tournament.gg, written in C# using dotnet core / razor pages (sorry - no client frameworks at present!)

Really keen to find a designer who would like to collaborate. Also have a film site (filmlovr.com  - built using Aurelia, NodeJS Express and ArangoDB - a sexy stack!) I want to revamp and looking to launch a casino site as well in near future.

If interested in any form of web development, or looking for a project to build a client app (mobile or web), come say hi!

Happy to talk microservices, cloud, serverless, graph dbs etc etc

**Comment by elcolie** [comment]
Try upgrading my favorite Django package
I want to upgrade it to Django2
https://github.com/elcolie/django-geoposition

I still looking forward to study ReactJS and CSS
Although I know ReactJS. I would like to gain more knowledge on UnitTesting as well.

**Comment by richsmith92** [comment]
Cardano (or something else crypto-related)
I'm going to try building Cardano SL and Daedalus wallet from source and figure out how to run them.

**Comment by nadam** [comment]
Cryptocurrency
Might work on the cryptozombies tutorial (Solidity) or libraries for exchanges' APIs in Java.

**Comment by Alainbriez** [comment]
Deploy OpenStack + Custom dashboard
We will work on the deployment of OpenStack then think and customize the dashboard UI, probably based on the Aurora Dashboard : https://github.com/entercloudsuite/aurora-ui

**Comment by blead** [comment]
RegChula Scheduler
- A side project I'm working on with a few people at Chula.
It's a web-based scheduler, pulling real data from the Registrar of Chula's website.
Frontend: https://github.com/phootip/reg-scheduler (Vue.js)
Backend: https://github.com/peawyoyoyin/reg-scheduler-back (Flask)
Deployed on GAE.

- Open to talk about almost any topic. Most of my experience is in web development though.

**Comment by brianwilsongh** [comment]
rust
playing with rust (still very new at it)

**Comment by tao-pr** [comment]
Computer Vision with OpenCV
To work on Active Appearance Model implementation on OpenCV3 (C++). The base repo for the project I'm working on is https://github.com/starcolon/aam-opencv3

Any discussion / collaboration are welcome!

**Comment by waf** [comment]
hackmap hacking

**Comment by Ipsta** [comment]
Using leaflet.js to display dynamic maps

**Comment by Ipsta** [comment]
Using leaflet.js to display dynamic maps
