### ISSUE TITLE
need to be able to configure the location of the repo/ticket to store data

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#5]
probably as part of the main comment

**Comment by waf** [comment]
what's the goal here?

**Comment by djay** [comment]
currently the datastore is the using a label and the same repo as the code is in right?
Ideally we have the code and data in seperate repos. Also the ticket with the data will need to change each week, so there is a historical record.

**Comment by djay** [comment]
@waf the goal is really covered by https://github.com/bkkhack/hackmap/issues/7 so I will close this
