### ISSUE TITLE
Prevent replies to main thread creating duplicate entries

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#54]
if someone replies to an email on github, or replies via github, then they can potentially appear twice in the project list if they had already added themselves.

# Options
1. Only show the first entry per person (or merge them somehow?)
2. Insert special code so only show entries inserted via the map
3. Use links to other tickets so the text is mainly in the other ticket and hopefully users reply there?

**Comment by waf** [comment]
Fixed in #61 (option 1). Thanks!
