### ISSUE TITLE
edit your details and it seems to revert

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#6]

**Comment by waf** [comment]
I've noticed the GitHub API does have an element of "eventual consistency." It's usually very good, but sometimes if I do some update / delete, the next poll can return out of date information. I've seen it take up to 15 seconds or so to get the new information.

We could update the polling logic to account for this. Something like "if the user has made an edit or update, delay the next poll for 15 seconds."

EDIT: I've implemented this, see the following excerpt: https://github.com/bkkhack/hackmap/blob/54b357f33253b11e1bd7cf5f06438d0f7b66b716/src/github-issues.js#L124-L130

**Comment by waf** [comment]
closing this for now as per my above edit. We can reopen if it happens again in the future.
