### ISSUE TITLE
April 2018 Hack Night

### ISSUE THREAD

**Issue by waf** [bkkhack/hackmap#63]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

If you know what you'll be hacking on, add it to the left.

The seating chart may not be up-to-date yet, but go ahead and add your plan or idea—when you arrive at the event, drag your picture to where you're sitting so others can find you. If you're not sure, you can join somebody else's hack, or ask @ches or @djay if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

**Comment by waf** [comment]
Test

**Comment by waf** [comment]
HackMap

**Comment by waf** [comment]
Test

**Comment by waf** [comment]
HackMap
Test

**Comment by waf** [comment]
HackMap
Test

**Comment by waf** [comment]
Rust and GTK
Rust programming language, experimenting with a cross-platform GTK GUI.

Demo project is a Slack GUI client

**Comment by gitegite** [comment]
Learning Haskell
via online resources, solving basic problems

**Comment by madelfino** [comment]
Thai Language Game
Probably using JavaScript, thinking of something like hangman to get used to manipulating strings with Thai characters

**Comment by ljdarj** [comment]
GHC hacking
Work on some GHC tickets.

**Comment by intouchpiti** [comment]
Learning Flask
via e-book: Flask Web Development (O'Reilly)

**Comment by intouchpiti** [comment]
Learning Flask
via e-book: Flask Web Development (O'Reilly)

**Comment by intouchpiti** [comment]
Learning Flask
via e-book: Flask Web Development (O'Reilly)

**Comment by ivoryblakk** [comment]
Javascript
Es6

**Comment by disconnect3d** [comment]
low level sec/pwndbg/manticore
I will either work on Pwndbg or Manticore projects or do some low level security CTF challenge

**Comment by davis1011001** [comment]
learn
i am new here, come to learn more. maybe next time

**Comment by nadam** [comment]
Blockchain

**Comment by Geowahaha** [comment]
Dialogflow, ML kit, Chatbot
I am beginner.from scratch I was created my own LINE platform chatbot for  Pet Pedigree registration I am try to play around with Dialogflow and ML kit. I was stuck with Webhook Nodejs Python. Your welcome  to join .

**Comment by ches** [comment]
@Geowahaha I'd forgotten to close the old board from last month's event, please if you don't mind recreate your topic on the Hack Map one more time so it posts for this month (you can copy-and-paste your description from [this page](https://github.com/bkkhack/hackmap/issues/63)).

Sorry for the trouble, work-in-progress software 😊

**Comment by Geowahaha** [comment]
Hi Ches

Thanks you your kind,. Sorry i m the beginner where i can update it again?

George

2018-05-14 19:23 GMT+07:00 Ches Martin <notifications@github.com>:
