### ISSUE TITLE
May 2018 Hack Night

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#64]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

If you know what you'll be hacking on, add it to the left.

The seating chart may not be up-to-date yet, but go ahead and add your plan or idea—when you arrive at the event, drag your picture to where you're sitting so others can find you. If you're not sure, you can join somebody else's hack, or ask @ches if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

**Comment by MitchellLizar** [comment]
HTML forms w/jQuery and JavaScript
no real focus this month - I'm developing my 'network' and experimenting with a different notepad

**Comment by Geowahaha** [comment]
Dialogflow Chat bot, Nodejs
Dialogflow, Chatbot
I am beginner.from scratch I was created my own LINE platform chatbot for Pet Pedigree registration I am try to play around with Dialogflow and google tools kit (). I was stuck with Webhook Nodejs Python. Your welcome to join .

**Comment by saguywalker** [comment]
Cryptocurrency Trading Bot with python
I will writing simple short trading  bot between Bitcoin and Ethereum on Binance with Python

**Comment by perjerz** [comment]
Nest.js (Typescript Node.js)
Write simple Nest.js app

**Comment by ianmere** [comment]
Crypto Trading bot
I will be making tweaks to my trading bot

**Comment by JesseSoldat** [comment]
Chaotic Storage Place App
Building a storage place solution for a fictional company with React / Node / Mongo

**Comment by madelfino** [comment]
Thai Language App Update
Last time I made a Thai language app (card matching game) I'd like to update it to allow users to use phonemic transcriptions instead of Thai script

**Comment by intouchpiti** [comment]
freecodecamp
Working through freecodecamp exercises.

**Comment by djay** [comment]
organising an event in june

**Comment by mrik23** [comment]
CTF
http://natasX.natas.labs.overthewire.org

**Comment by niponpant0ng** [comment]
Kafka101

**Comment by luke** [comment]
Giphy TV
cat videos
