### ISSUE TITLE
Aug 2018 Hacknight 

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#67]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

If you know what you'll be hacking on, add it to the left.

The seating chart may not be up-to-date yet, but go ahead and add your plan or idea—when you arrive at the event, drag your picture to where you're sitting so others can find you. If you're not sure, you can join somebody else's hack, or ask @ches if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

**Comment by juhog** [comment]
Hugo - static site generator
https://gohugo.io/

Hugo is static site generator based on markdown. Let's try out some of the key features and see what we can do with Hugo.

- basic content management features (content types, taxonomies, menus)
- dynamic API-driven content
- shortcodes ("markdown's hidden superpower")
- SEO, commenting, analytics
- multi-language features
- output as JSON

**Comment by djay** [comment]
Improve hackmap
Try to implement persistent projects and/or fix the map sizing.

**Comment by elcolie** [comment]
Self study on DeepLearning
Watch Udemy class "Deep learning in Python"
I do taking note on the paper in order to boost up my understanding and help me memorize the formulas.

**Comment by ad19** [comment]
Julia plotting with plots.jl
Inspired by an Udemy course that I’m studying, I’m learning how to plot with Julia.

**Comment by madelfino** [comment]
InfoSec
Working through the Udacity course on Information Security

**Comment by caspar-goeke** [comment]
Do Something
Not work related stuff

**Comment by linusidom** [comment]
Unit Testing in Django for Fitness App
Writing Unit tests for my app, if you have experience with mockup for testing entries in the DB or using setup/teardown for client/db entry creation would be much appreciated.

Fitness App Details:
Enter your personal Goals
Track your expenses
Track your food and calories
Track your exercise
Get a report of how many calories per $ you get
How close the quality of food you get for your money is to your goals
Where you could be in regards to weight in the next Week, and Month if you keep it up

Invite a trainer to help you keep track of progress

http://modisidom.herokuapp.com/

Also looking for side projects.  If you have any in mind or know of people in need of a freelance programmer, let me know.

speak read and write thai as well

**Comment by pobch** [comment]
Studying/Building stuffs with MERN stack

**Comment by juacompe** [comment]
Sortable table on rails

**Comment by sthapaun** [comment]
UE4 101

**Comment by kidchenko** [comment]
JS

**Comment by n1ghtcoder** [comment]
ETHBKK Ethereum Meetup
![Image](https://secure.meetupstatic.com/photos/event/d/3/a/0/highres_474174176.jpeg)

Come have some pizza and talk about how Ethereum works, why it works, and what it’s enabling with other Bangkok-based Ethereum geeks and enthusiasts.

[meetup.com link](https://www.meetup.com/Ethereum-Meetup-in-Bangkok/events/254233575/)
