### ISSUE TITLE
Sept BKK Hack

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#69]
Welcome to BKK/hack!  (Best viewed on  https://bkkhack.github.io/hackmap)

A hack is what you'd really like to work on if you can. 

1. Add your idea on the left
2. Drag your face onto the map. Just pick anywhere or next to someone doing something similar.

Do this as soon as you RSVP and update it often.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

**Comment by korrio** [comment]
สนใจจ้า
อยากมีส่วนร่วม

**Comment by djay** [comment]
vuetify.js and PWA
Making a map based app.

**Comment by wasurocks** [comment]
Python Starter
Without much experience coding, can I still join? I'm still studying in high school.

**Comment by ches** [comment]
@GreenColoredLife Yes, sure!

**Comment by Wenbo888** [comment]
build a line chat bot with python

**Comment by wgx731** [comment]
**[DrSpring](https://github.com/wgx731/dr-spring)** - Spring Boot with different RPC backend (e.g. GRPC, apache Dubbo, Logom)
Research and compare Spring Boot integration with different RPC frameworks.

**Comment by djay** [comment]
https://hacktoberfest.digitalocean.com/

**Comment by anthonysousa** [comment]
WordPress productized business
Work on a side business for WordPress productized support.

**Comment by mkster** [comment]
Make a game with Pico8 in Lua

**Comment by Qodibop** [comment]
build a market-place with Vue.js and Firebase.
https://medium.com/@anas.mammeri/vue-2-firebase-how-to-build-a-vue-app-with-firebase-authentication-system-in-15-minutes-fdce6f289c3c

**Comment by harrytyl** [comment]
Deep learning vs. Stats
Empirically comparing deep learning (Python) and statistical (R) models for a space-time dataset.

**Comment by SoulSkare** [comment]
VueJS - Express
Build a small web app with VueJS for it's front end.

A place to add/edit/remove email templates

Homepage Welcome
Register/Login
Template dashboard and flow

**Comment by elcolie** [comment]
Kubenetes
Is it possible to scale up the cluster by python programming? Like I create/terminate a subprocess in it

**Comment by djay** [comment]
vuejs+githubapi: help wanted improving hackmap
https://github.com/bkkhack/hackmap/issues

**Comment by keithrbennett** [comment]
Issues of DNS, Redirecting, Port Config
I have a domain pointing to a blog on Github Pages and would like to use subdomains and other routes to point to different locations outside of Github Pages. If anyone is knowledgeable about this and can help it would be appreciated. Another option is to host the blog myself, but that introduces other issues.

**Comment by dwsmith1983** [comment]
docker, python, or c++

**Comment by panbor** [comment]
Python Learning(starter)

**Comment by wasurocks** [comment]
@panbor Hi! I'm in the same boat as you. Can I join?

**Comment by Sawaphob** [comment]
Data(Python)

**Comment by blead** [comment]
Setting up Rocket.Chat
- setting up Let's Encrypt for HTTPS too

**Comment by juhog** [comment]
Node.js practice
Practicing Node.js basics on a dummy app (EJS, Handlebars, MongoDB)

**Comment by steve1rm** [comment]
Android
Android App Develop

**Comment by panbor** [comment]
IT Systems Integration Architecture

**Comment by ganeshbm19** [comment]
Coworking Space Management Software
CoAider is a technology platform for smart shared workspaces. Our software powers co-working and serviced office spaces.

For details click the following link: https://provion.in/coaider

**Comment by elcolie** [comment]
Build ChatBot with ProgramY
Build a Chatbot with ProgramY
https://github.com/keiffster/program-y
