### ISSUE TITLE
April 2019 Hack Night

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#74]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

### How This Works

A hack is what you'd like to do (or learn) at hack night.

1. Add your idea on the left. In advance of the Meetup date is great.
1. Drag your picture onto the seating map when you arrive. Wherever you wish, or near someone doing something similar.

If you're not sure, you can join someone else's hack, or ask the organizers if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

Have fun!

**Comment by djay** [comment]
learn react
so I can decide how to use https://github.com/plone/volto in plone

**Comment by crskkk** [comment]
Business Development
Project Management
Cost Structuring
Forecasting
Business Model

**Comment by ljdarj** [comment]
libarchive
Working on improving the zip support

**Comment by alderaan** [comment]
Reinforcement Learning in Unity
Create a simple Reinforcement Learning agent in the free game Engine Unity.

**Comment by jonli29** [comment]
Streaming app mobile
I want start to develop using wowza.com using api rails and react native

**Comment by wasinator** [comment]
Create mobile app using NativeScriptVue
https://nativescript-vue.org/

**Comment by elibenjii** [comment]
React Native
Build app like Agoda.
@jonli29, you can get inspiration from my app similar to your project: https://github.com/NielsDom/React-sound-app

**Comment by dwsmith1983** [comment]
Not sure
Bother others

**Comment by juhog** [comment]
Vue.js & Vuetify

**Comment by jean** [comment]
elm
Get it up and running

**Comment by lauriii** [comment]
Drupal
I'm working on modernizing Drupal's admin UI using React. Happy to collaborate with anyone who's interesting in this or any other topic around Drupal 🥳

**Comment by morishuz** [comment]
deep learning (using python)
playing with CNN's and GAN's in Keras

**Comment by htkhuang** [comment]
Design Researcher + python learner

**Comment by elcolie** [comment]
Design Neural Network to read Thai

**Comment by 5zzang** [comment]
DevOps
Docker, AWS, Centralized Logging and etc.

**Comment by Narong-Kanthanu** [comment]
Media server (using node.js)

**Comment by ghost** [comment]
Storyteller
I am good at finding angles to explore and producing outputs that really speak to the intended audience

**Comment by ivybridge-3c33** [comment]
Kubernetes

**Comment by ghost** [comment]
React, Nodejs, GraphQL

**Comment by elcolie** [comment]
Thai OCR with PyTorch

**Comment by hanachan1026** [comment]
Laravel

**Comment by hanachan1026** [comment]
Laravel

**Comment by nyck33** [comment]
CNN image classifier
Using transfer learning and classifying images from Imagenet but we can start smaller with Cifar images.  We will use Tensorflow and Keras.  (But sorry, I'm still learning Tensorflow 2.0 so it might be a bit dated).

**Comment by nmewz** [comment]
UX design + Python

**Comment by ntchjb** [comment]
Learn flutter
Build a very simple counter app using flutter

**Comment by mortend** [comment]
Fuse app-dev
Plan to work on an app using Fuse Open framework, fuseopen.com.

**Comment by allVentures** [comment]
foto sharing app for photographers
I have this project which i started as part of Python Bootcamp. 
Photo sharing application for photography enthusiasts; Never had time to finish it but if anyone is willing to work on it, I'll be happy to present it.
the code is available at:
https://github.com/allVentures/fotoPX-Picture-Sharing-Application-
SQLDump and picture files are avilable at:
https://drive.google.com/open?id=1x_MVttvbK1_Slt2Spa51Pp5fNt2Fg8jK

**Comment by jinusean** [comment]
Learn Deep Learning / Python
Tech skills:
Javascript, Vue, Nativescript

**Comment by toastal** [comment]
PureScript + Halogen (fp front-end)
I'm working on a project for the school I'm at to build a class schedule. There's no reason to use PureScript other than I want to. If you like functional programming, let's chat.

**Comment by andyfusniak** [comment]
Vue.js/Vuetify with Go REST API backend

**Comment by namwa** [comment]
Vuejs/Vuetify

**Comment by mvperez** [comment]
F#

**Comment by ches** [comment]
Machine Learning platform research
Learning about some open source solutions for (parts of) machine learning development and deployment pipelines, like [Seldon](https://github.com/SeldonIO/seldon-core).

For more about the problems these try to solve, see for example Uber or Airbnb's:

- https://eng.uber.com/michelangelo/
- https://www.youtube.com/watch?v=yBiyT1azwtQ

**Comment by yrashk** [comment]
We'll see

**Comment by yrashk** [comment]
Maybe ESP32?
I can bring this little piece of microcontroller fun with me

**Comment by yrashk** [comment]
Maybe ESP32?

**Comment by gregbkr** [comment]
Learn UX design and frontend
Want to learn : React, nodejs, ux design, golang backend. 

Know: devops: docker, kubernetes, Google cloud, elk, ansible, ethereum Blockchain.

**Comment by StrikerUnit** [comment]
Not Sure Yet.

**Comment by StrikerUnit** [comment]
Not Sure Yet

**Comment by giappv** [comment]
Exploring Bangkok
Connecting to Bangkok

**Comment by giappv** [comment]
Hacking Bangkok
Hacking Bangkok

**Comment by nadam** [comment]
Java stuff

**Comment by nadam** [comment]
Java

**Comment by sosoms** [comment]
blockchain
theory
