### ISSUE TITLE
May 2019 Project Night

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#77]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

### How This Works

A hack is a project you'd like to do (or learn) at hack night.

1. Add your idea on the left. In advance of the Meetup date is great.
1. Drag your picture onto the seating map when you arrive. Wherever you wish, or near someone doing something similar.

If you're not sure, you can join someone else's hack, or ask the organizers if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

Have fun!

**Comment by juhog** [comment]
Headless Drupal + JSON:API + React

**Comment by jraut** [comment]
Elixir backend & ELM front
Try to use elixir as a game backend

**Comment by khammong** [comment]
React Frontend
I'm a front-end developer.

**Comment by iliasbhal** [comment]
Ilias Bhallil
I'm a full-stack TS developer: React / Express.
I'm also a Dart/Flutter Dev enthusiast.

**Comment by JuanPabloArbelaez** [comment]
Flutter learning
Learn to develop on Flutter

**Comment by toastal** [comment]
PureScript + RPG game
PureScript is a Haskell-like functional language that compiles to JavaScript (and others), but with a different type hierarchy and strict evaluation.

I'm gonna start working on a game with a friend back home. I'll be setting up and looking at making a character and enemy with stats as well as defining the game grammar and probably just printing to screen for now.

I just finished a project for my language visa school using PureScript, so I should be mostly ready to roll.
https://gitlab.com/toastal/lx-flight-board
https://www.mylxonline.com/flightboard/

I may also take another look at the Gluon language.

**Comment by ches** [comment]
Tinkering with home automation
Perhaps digging into Home Assistant a bit. Probably nothing too sophisticated with custom tech, I'm not much more than an average consumer in this area yet.

**Comment by thaxy** [comment]
Networking, Bash, Python, Linux, 2FA
* Have to talk to some people (avoiding eye strain)

* Setting up my new phone, have to migrate all my google authenticator keys. Maybe having a deeper look into how things work in detail

* Improving my backup scripts written in python/bash to automatically backup postgres and media data on my ubuntu server. This includes file uploads to other systems and reporting by mail

* Always happy to talk about docker <3

**Comment by PabloRomanH** [comment]
Learning WebAssembly!
Look for the bald guy with a grey stripped t-shirt.
Let's make our first "Hello World", and then some project to learn the basics of WebAssembly.

**Comment by tmrwltd** [comment]
PHP
PHP Developer; Try to learn ReactJS now ...

**Comment by Objectoop** [comment]
blockchain
Discussion about Blockchain

**Comment by sidopsdev** [comment]
Blockchain and Cryptocurrency using py
Following this tutorial
https://medium.com/@erickzhang/https-medium-com-erickzhang-lets-build-a-blockchain-network-and-your-own-cryptocurrency-using-python-4b2620e61b76

**Comment by skasidej** [comment]
Python / PHP
Anything - trying to learn Django's / ML / etc.

**Comment by sosoms** [comment]
Blockchain​hack

**Comment by wasurocks** [comment]
Android Learning / Make some basic App (No idea what lol) 
I'm starting to learn android and think that making a basic application (a native app with Java in Android Studio) would be useful along the way.

**Comment by brainless** [comment]
Python/React MVP builder
I have been working with Python and React for a few years. I think many people want a simple want to start building their software MVP.

I would like to build a simple way for people to start a full-stack app using Python (backend) and React (frontend).

**Comment by sychedelix** [comment]
Automatic Custom Events Tracking / JS

**Comment by sychedelix** [comment]
Auto Website Events Tracking / JS
Automatically track your customer’s interactions with your website and analyze your user journey without writing any code.

**Comment by patc11** [comment]
Vue js/asp.net
Trying to create website using vue ja and asp.net

**Comment by cliu3322** [comment]
React, node.js, blockchain

**Comment by tkunanuntakij** [comment]
Tackle some Kaggle problem
I will spend some time trying to solve some Kaggle problem (probably the challenge that've already ended). Gain more practical experience in Data Science and ML.
