### ISSUE TITLE
November 2019 Project Night

### ISSUE THREAD

**Issue by ches** [bkkhack/hackmap#79]
Welcome to BKK/hack!

(On github.com? Try [our hackmap instead!](https://bkkhack.github.io/hackmap/))

### How This Works

A hack is a project you'd like to do (or learn) at hack night.

1. Add your idea on the left. In advance of the Meetup date is great.
1. Drag your picture onto the seating map when you arrive. Wherever you wish, or near someone doing something similar.

If you're not sure, you can join someone else's hack, or ask the organizers if you have any questions.

If you've found a bug in our hackmap, please [report it here](https://github.com/bkkhack/hackmap/issues).

Have fun!

**Comment by theboman** [comment]
Simple bus schedule app - React /Native
I was going to create a simple mobile app (iOS and Android) for our small private bus at our apartment complex. 

for the app
 React / Native 

for the admin probably (start simpler than might decide to make more complex... )
 vanilla javascript or React

Postgres DB or could even be MongoDB.

Is anyone else looking to learn React / Javascript? I would love to mentor and be mentored I have about 1-year self-taught experience.


I live by On-Nut BTS
-Bo

**Comment by toastal** [comment]
PureScript SPA
I want a UI to help me with my taxes and other BS financial stuff because the US sucks. It'll be backed with PouchDB to sync store data and the front-end will be Halogen.

Alternatively, I may look at forking PixelFed (and PRing?) to include features I want to use it as an alternative to the proprietary Flickr and Instagram apps for hosting and letting others engage and share my images.

**Comment by chayapan** [comment]
Income Prediction with Python
I will be working on a machine learning model to predict bank customer's income. I plan to use Python in IPython notebook environment, but I'm open to try other tools if there're interests.

**Comment by chayapan** [comment]
Income Prediction with Python
I will try to use Jupyter Notebook to build machine learning model to predict bank customer's income.
