### ISSUE TITLE
Capture client-side js errors

### ISSUE THREAD

**Issue by waf** [bkkhack/hackmap#8]
They could post to some other issue or comment

**Comment by ches** [comment]
Maybe we can use one of the existing hosted exception tracking services with JS client libraries, like [Rollbar]? I would imagine we'd fit in their free plan.

[Rollbar]: https://rollbar.com/

**Comment by waf** [comment]
@ches and @djay, I've invited you a RollBar group for tracking hackmap errors. The URL is https://rollbar.com/bkkhack/hackmap/. We're using their free plan.
