### ISSUE TITLE
would be good for an organiser to move others around

### ISSUE THREAD

**Issue by djay** [bkkhack/hackmap#9]
if they know their location isn't accurate

**Comment by waf** [comment]
An organiser should also be able to delete others, as per https://github.com/bkkhack/hackmap/issues/14

**Comment by djay** [comment]
I think usecase is where I walk around, ask who they are and instead of
telling them to log back in and move them I move their location for them.
At least for the first few to get it going.

**Comment by djay** [comment]
@waf the other reason this would be good is that I want to start creating theme tables. As projects get added I would drag the people onto the map and group them myself basic on general topic, at the same time update the map with a label for that table like "mobile dev" or "node js" or "learning programming" etc. This should in tern encourage more people to put their projects down and join the table
